lecture/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todo/',include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.urls import path
from todo.views import IndexView, detail,create,delete,create_item, todo_update,update,update_item,delete_item,todo_update
app_name='todo'
urlpatterns = [
    # path('', index, name='index'),
    path('',IndexView.as_view(), name='index'),
    path('<int:list_id>/', detail, name='list_detail'),
    path('create/',create,name='list_create'),
    path('<int:list_id>/delete',delete,name='list_delete'),
    path('<int:list_id>/updatelist',update,name='list_update'),
    path('<int:list_id>/createitem/',create_item,name='item_create'),
    path('<int:list_id>/<int:item_id>/',update_item,name='item_update'),
    path('<int:list_id>/<int:item_id>/delete',delete_item,name='item_delete'),
    path('<int:list_id>/update',todo_update,name='update')

]

todo/models.py
from django.db import models

# Create your models here.

class Todolist(models.Model):
    list_name = models.CharField(max_length=100)
    def __str__(self):
        return f"{self.list_name}"


class Todoitem(models.Model):
    title = models.CharField(max_length=100)
    checked = models.BooleanField(default=False)
    due_date = models.DateTimeField(null = True)

    todo_list = models.ForeignKey(to=Todolist, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.todo_list.list_name}: {self.title}"

todo/views.py
from django.http.response import Http404
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.template.context import Context
from django.views import generic
from .models import Todolist, Todoitem

class IndexView(generic.ListView):
    template_name = 'todo/index.html'
    context_object_name = 'todolists'

    def get_queryset(self):
        return Todolist.objects.all()

def detail(request, list_id):
    try:
        todolist = Todolist.objects.get(id=list_id)
    except Todolist.DoesNotExist:
        raise Http404("this list does not exist")
    items_list = Todoitem.objects.filter(todo_list = todolist)
    context = {
        'todolist' : todolist,
        'items_list' : items_list
        }
    return render(request, 'todo/detail.html',context)

def create(request):
    if request.method == 'GET':
        return render(request, 'todo/createlist.html')
    
    name = request.POST["name"]
    res = Todolist.objects.filter(list_name=name)
    if len(res)>0:
        messages.error(request,'List already present')
        return render(request, 'todo/createlist.html')
    else:
        Todolist.objects.create(list_name=name)
        lists = Todolist.objects.all()
        context = {
            'todolists' : lists
        }
        return render(request, 'todo/index.html', context )

def delete(request,list_id):
    try:
        todolist = Todolist.objects.get(id=list_id)
        res = Todolist.objects.filter(id=list_id)
    except Todolist.DoesNotExist:
        raise Http404("this list does not exist")
    res.delete()
    lists = Todolist.objects.all()
    context = {
        'todolists' : lists
    }
    return render(request, 'todo/index.html', context )

def update(request,list_id):
    try:
        todolist = Todolist.objects.get(id=list_id)
        res = Todolist.objects.filter(id=list_id)
    except Todolist.DoesNotExist:
        raise Http404("this list does not exist")
        
    if request.method == 'GET':
        context = {
        'todolist' : todolist,
    }
        return render(request, 'todo/updatelist.html',context)
    
    name = request.POST["name"]
    try:
        check = Todolist.objects.get(list_name=name)
        messages.error(request,'List already present')
        context = {
            'todolist' : todolist,
        }
        return render(request, 'todo/updatelist.html',context)
    except:
        res.update(list_name=name)
        lists = Todolist.objects.all()
        context = {
            'todolists' : lists
        }
        return render(request, 'todo/index.html', context )


def create_item(request, list_id):
    todolist = Todolist.objects.get(id=list_id)
    if request.method == 'GET':
        context = {
        'todolist' : todolist
        }
        return render(request, 'todo/createitem.html',context)

    todolist = Todolist.objects.get(id=list_id)
    title1 = request.POST["title"]
    date = request.POST["duedate"]
    res = Todoitem.objects.filter(title=title1,todo_list=todolist)
    if len(res)>0:
        messages.error(request,'Item already present')
        context = {
        'todolist' : todolist
        }
        return render(request, 'todo/createitem.html',context)
    else: 
        Todoitem.objects.create(title=title1,checked=False,due_date=date,todo_list=todolist)
        lists = Todolist.objects.all()
        context = {
            'todolists' : lists
        }
        return render(request, 'todo/index.html', context )

def update_item(request,list_id,item_id):
    try:
        todolist = Todolist.objects.get(id=list_id)
        todoitem = Todoitem.objects.get(id=item_id,todo_list=todolist)
        item = Todoitem.objects.filter(id=item_id,todo_list=todolist)
    except Todolist.DoesNotExist:
        raise Http404("this list does not exist")
    except Todoitem.DoesNotExist:
        raise Http404("this item does not exist")
    if request.method == 'GET':
        context = {
        'todolist' : todolist,
        'todoitem' : todoitem
        }
        return render(request, 'todo/updateitem.html',context)
    title1 = request.POST["title"]
    date = request.POST["duedate"]
    if request.POST["status"] == 'on':
        status=True
    else:
        status=False

    item.update(title=title1,checked=status,due_date=date,todo_list=todolist)
    lists = Todolist.objects.all()
    context = {
        'todolists' : lists
    }
    return render(request, 'todo/index.html', context )


def delete_item(request,list_id,item_id):
    try:
        todolist = Todolist.objects.get(id=list_id)
    except Todolist.DoesNotExist:
        raise Http404("this list does not exist")
    try:
        todoitem = Todoitem.objects.get(id=item_id,todo_list=todolist)
        res = Todoitem.objects.filter(id=item_id,todo_list=todolist)
    except Todoitem.DoesNotExist:
        raise Http404("this item does not exist")

    res.delete()
    items_list = Todoitem.objects.filter(todo_list = todolist)
    context = {
        'todolist' : todolist,
        'items_list' : items_list
    }
    return render(request, 'todo/detail.html', context )

def todo_update(request,list_id):
    todolist = Todolist.objects.get(id=list_id)
    data=request.POST
    todoitems = Todoitem.objects.filter(todo_list=todolist)
    todoitems.update(checked=False,todo_list=todolist)
    for item in data:
        try:
            todoitem = Todoitem.objects.get(title=item,todo_list=todolist)
            res = Todoitem.objects.filter(title=item,todo_list=todolist)
            print(res)
            res.update(checked=True,todo_list=todolist)
        except Todoitem.DoesNotExist:
            pass
    lists = Todolist.objects.all()
    context = {
        'todolists' : lists
    }
    return render(request, 'todo/index.html', context )

todo/templates/todo/createitem.html
<form action="{% url 'todo:item_create' todolist.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <h1>create new item</h1>
        <label for="title">Title : </label><input type="text" name="title" id="title" required>
        <label for="duedate">Due Date : </label><input type="datetime-local" name="duedate" id="duedate" required>
        <input type="submit">
    </fieldset>
</form>
{% for message in messages %}
    <p style="color:red;">{{ message }}</p>
{% endfor %}
<a href='/todo'><button>BACK</button></a><br>

todo/templates/todo/createlist.html
<form action="{% url 'todo:list_create' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <h1>create new list</h1>
        <input type="text" name="name" id="name" required>
        <input type="submit">
    </fieldset>
</form>
{% for message in messages %}
    <p style="color:red;">{{ message }}</p>
{% endfor %}
<a href='/todo'><button>BACK</button></a><br>

todo/templates/todo/detail.html

<div style="display: flex; flex-direction: row; justify-content: space-between; align-items: center;" id='container'>
    <div class="item"><h1>{{ todolist.list_name}}</h1></div>
    <div class="item"><a href='/todo/{{todolist.id}}/updatelist'><button>CHANGE NAME</button></a></div>
    <div class="item"><form action="{% url 'todo:list_delete' todolist.id %}" method="GET">
        {% csrf_token %}
            <input type="submit" value="DELETE">
    </form></div>
</div>

<form action="{% url 'todo:update' todolist.id %}" method="post">
    {% csrf_token %}
    <fieldset>
<ul>
    {% for item in items_list %}
    <li>
        <p style="size: 21px; color: blue;"><a href="/todo/{{todolist.id}}/{{item.id}}">{{item.title}}</a>
        {% if item.checked == True %}
        <input type="checkbox" name={{item.title}} value={{item.title}} checked="checked" />
        {% else %}
        <input type="checkbox" name={{item.title}} value={{item.title}} />
        {% endif %}
    </p>
    Due {{item.due_date}}
        
    </li>
    {% endfor %}
</ul>
<input type="submit" value="UPDATE">
</fieldset>
</form>
<a href='/todo/{{todolist.id}}/createitem'><button>ADD ITEM</button></a>


todo/templates/todo/index.html
<h1>ToDo APP</h1>
{% if todolists %}

    <ul>
        {% for todolist in todolists %}
        <li><a href="/todo/{{todolist.id}}">{{todolist.list_name}}</a></li>
        {% endfor %}
    </ul>

    <a href='/todo/create'><button>CREATE</button></a>


{% endif %}

todo/templates/todo/updateitem.html
<form action="{% url 'todo:item_update' todolist.id todoitem.id%}" method="post">
    {% csrf_token %}
    <fieldset>
        <h1>{{todoitem.title}}</h1>
        <label for="title">Title : </label><input type="text" name="title" id="title" placeholder={{todoitem.title}} value={{todoitem.title}} required><br><br>
        <label for="duedate">Due Date : </label><input type="datetime-local" name="duedate" id="duedate" value={{todoitem.due_date}} required><br><br>
        {% if todoitem.checked == True %}
        <label for="status">Checked</label><input type="radio" name="status" id="status" checked required><br><br>
        {% else %}
        <label for="status">Checked </label><input type="radio" name="status" id="status" required><br><br>
        {% endif %}
        <input type="submit" value="Update">

    </fieldset>
</form>
<form action="{% url 'todo:item_delete' todolist.id todoitem.id %}" method="GET">
    {% csrf_token %}
        <input type="submit" value="Delete">
</form>
{% for message in messages %}
    <p style="color:red;">{{ message }}</p>
{% endfor %}

todo/templates/todo/updatelist.html
<form action="{% url 'todo:list_update' todolist.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <h1>Enter new name for the list</h1>
        <input type="text" name="name" id="name" required>
        <input type="submit">
    </fieldset>
</form>
{% for message in messages %}
    <p style="color:red;">{{ message }}</p>
{% endfor %}

<a href='/todo'><button>BACK</button></a><br>